* PenSieve - A filesystem interface to large language models

https://semiosis.github.io/pensieve/

The idea with PenSieve is that you drag and drop files representing thoughts.

What goes in also affects what comes out, and may be used to train the model.

A filesystem abstraction for prompting, using =Pen.el= as the prompting server.

** Installation
Download from http://example.com/FIXME.

** Usage
FIXME: explanation

#+BEGIN_EXAMPLE
    $ java -jar pensieve-0.1.0-standalone.jar [args]
#+END_EXAMPLE

** Options
FIXME: listing of options this app accepts.

** Examples
...

** License
Copyright © 2022 FIXME

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following
Secondary Licenses when the conditions for such availability set forth
in the Eclipse Public License, v. 2.0 are satisfied: GNU General Public
License as published by the Free Software Foundation, either version 2
of the License, or (at your option) any later version, with the GNU
Classpath Exception which is available at
https://www.gnu.org/software/classpath/license.html.
