* =PenSieve= - A file system abstraction for prompting Large Language Models

=PenSieve= is essentially an imaginary file
system based on prompting Large LMs, using
=Pen.el= as the prompting server, or more accurately, a file system interface to prompting.

In layman's terms, you drag and drop files
representing thoughts, or similarly high-
dimensional entities.

You could, for example, drag memories between
chatbots, and that would influence each of
their personalities.

File system units such as files and directories
may also keep metadata, such as a prompting
history, which is used to guide the prompting.

What goes in also affects what comes out, and
may be used to train the model.

+ Asking Dumbledore for help with the design :: https://asciinema.org/a/Wl8ti5oE7YK9bdwb3gzsxzB4w

** Installation
Download from http://github.com/semiosis/pensieve.

Run =Pen.el= in the background. It's the prompting server that powers =PenSieve=.

Download =Pen.el= from http://github.com/semiosis/pen.el.

Read about =PenSieve= here: https://semiosis.github.io/pensieve/.

** Usage
*** Initiate the file system like so
Just provide the directory path, and the
directory will be mounted imaginarily.

#+BEGIN_SRC sh -n :sps bash :async :results none
  # A chatbot's memories
  pensieve "$HOME/Dumbledore's Adventures/"

  # Alternative invocation:
  java -jar pensieve-0.1.0-standalone.jar "/tmp/NSA Top-Secret files/"

  # This could be interesting
  pensieve "$HOME/The memories of trees/"
#+END_SRC

** License
Copyright © 2022 Semiotic LLC

#+BEGIN_SRC text -n :async :results verbatim code
                      GNU AFFERO GENERAL PUBLIC LICENSE
                         Version 3, 19 November 2007
  
   Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
   Everyone is permitted to copy and distribute verbatim copies
   of this license document, but changing it is not allowed.
  
  ...
#+END_SRC

[[./LICENSE]]

=AGPLv3= or later.

Project originally derived from =ruse=, which is also =AGPL3=.

https://github.com/ahungry/ruse/blob/master/README.md