* Design
** Simple mapping to Pen.el
I want _emergent behaviour_.

Therefore, base the prompts entirely on file names for the moment.

In the future, edit filesystem attributes,
etc.

** Prompting
*** Initiate the filesystem like so
**** A chatbot's memories
#+BEGIN_SRC sh -n :sps bash :async :results none
  pensieve "Dumbledore's Memories"
#+END_SRC

**** The memories of people
#+BEGIN_SRC sh -n :sps bash :async :results none
  pensieve "The memories of trees"
#+END_SRC

*** Each directory has a prompt memory
I should tie a prompt function to each directory?
Allow to keep individual memory banks.

Make this an argument to the prompt functions.

*** The prompt
#+BEGIN_SRC text -n :async :results verbatim code
  This is the filesystem for exploring <what>:
#+END_SRC

** Use-cases
*** Analysis of thoughts
"I use the Pensieve. One simply siphons the
excess thoughts from one's mind, pours them
into the basin, and examines them at one's
leisure. It becomes easier to spot patterns
and links, you understand, when they are in
this form."

*** Generating programming projects

*** 